### ISSUE TITLE
The Psalms' Custom Marked 2 Style

### ISSUE THREAD

**Issue by extratone** [extratone/bilge#378]
Updated `03132023-103219`

- [**Gist**](https://gist.github.com/8ec87b927a82323b6bcac95837497060)
- [Pastery](https://www.pastery.net/whfamj/)
- [SnippetsLab](snippetslab://snippet/6095D562-10B1-49FB-B1C4-DDFA6FD46518/)
- [WTF](https://davidblue.wtf/drafts/2E33550B-2152-4030-B163-6BA291B3D389.html)
- [Local](shareddocuments:///private/var/mobile/Library/Mobile%20Documents/com~apple~CloudDocs/Written/2E33550B-2152-4030-B163-6BA291B3D389.md)
- [Draft](drafts://open?uuid=2E33550B-2152-4030-B163-6BA291B3D389)

---

## Social

<iframe src="https://mastodon.social/@DavidBlue/110016691900629440/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script src="https://static-cdn.mastodon.social/embed.js" async="async"></script>

- [Mastodon](https://mastodon.social/@DavidBlue/110016691900629440)

--- 

## Gist

<script src="https://gist.github.com/8ec87b927a82323b6bcac95837497060.js"></script>

## Source

```css
/* 
   This document has been created with Marked.app <http://markedapp.com>, Copyright 2011 Brett Terpstra
   Please leave this notice in place, along with any additional credits below.
   ---------------------------------------------------------------
   Title: The Psalms
   Author: David Blue - https://davidblue.wtf/contact
   Description: Replicating the reading experience of bilge.world.
*/

@import url('https://use.typekit.net/kst2rrh.css');

body {
    -webkit-font-smoothing: antialiased;
    font-family: adobe-caslon-pro, serif;
    font-weight: 400;
    font-style: normal;
    background-color: #FFF4E6;
}

html>body {
    font-size: 13px;
    font-family: adobe-caslon-pro, serif;
    font-weight: 400;
    font-style: normal;
    background-color: #FFF4E6;
}

li {
    font-size: 110%;
}

li li {
    font-size: 100%;
}

li p {
    font-size: 100%;
    margin: .5em 0;
}

h1 {
    color: #00006b;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 900;
    font-size: 2em;
}

h2 {
    color: #00006b;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 700;
    font-size: 1.4em;
}

h3 {
    color: #4078f2;
    font-family: proxima-nova-extra-condensed, sans-serif;
    font-weight: 600;
    font-size: 1.3em;
}

h4 {
    color: #f43f32;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    font-size: 1em;
}

h5 {
    color: #662545;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    font-size: 1em;
}

h6 {
    color: #80808C;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    font-size: .85em;
}

body,p {
    color: #1c0021;
    font-family: adobe-caslon-pro, serif;
    font-weight: 400;
    font-style: normal;
    font-weight: 400;
    line-height: 155%;
    font-size: 1.1em;
    color: #000001;
    padding-left: 0.5rem;
    padding-right: 0.5rem;
    word-wrap: break-word;
}

td,div {
  color: #6f6f6f;
  font-family: proxima-nova-condensed, sans-serif;
  font-weight: 400;
}

h1,h2,h3,h4,h5,h6 {
    line-height: 1.5em;
}

a {
    -webkit-transition: color .2s ease-in-out;
    -moz-transition: color .2s ease-in-out;
    -o-transition: color .2s ease-in-out;
    -ms-transition: color .2s ease-in-out;
    transition: color .2s ease-in-out;
    color: #00006b;
    text-decoration: none;
}

a:hover {
    color: #f43f32;
}

.footnote {
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 700;
    /*vertical-align: sub; */
    margin: -4px 0px 0 0;
    color: #da2573;
    font-size: 0.8em;
    line-height: 0.1em;
    text-decoration:underline #FF0000;
}

.footnote-ref {
    margin-left:15px;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 700;
    /* margin-left:2.5px; */
    color: #da2573;
    font-size: 1.15em;
    /* text-decoration:underline #FF0000; */
}

.footnote-ref-text {
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    color: #1c0021;
    font-size: 1em;
    /* border-top: #00006b dotted 1px; */
}

#wrapper img {
    max-width: 100%;
    height: auto;
}

dd {
    margin-bottom: 1em;
}

li > p:first-child {
    margin: 0;
}

code {
    font-size: 0.85em;
    color: #1c0021;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
}

ul ul,ul ol {
    margin-bottom: .4em;
}

caption,col,colgroup,table,tbody,td,tfoot,th,thead,tr {
    border-spacing: 0;
}

table {
    background-color: #FFFdeb;
    font-size: 0.8em;
    line-height: 1.2em;
    color: #1c0021;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    border: 1px solid #f43f32;
    border-radius: 1px;
    border: 1px solid;
    border-color: #da2573;
}

caption {
    display: table-caption;
    font-weight: 700;
}

col {
    display: table-column;
}

colgroup {
    display: table-column-group;
}

tbody {
    display: table-row-group;
}

tfoot {
    display: table-footer-group;
}

thead {
    display: table-header-group;
}

td,th {
    display: table-cell;
}

tr {
    display: table-row;
}

table th,table td {
    font-size: 1.1em;
    line-height: 23px;
    padding: 0 1em;
}

table thead {
    background: rgba(0,0,0,0.15);
    border: 1px solid rgba(0,0,0,0.15);
    border-bottom: 1px solid rgba(0,0,0,0.2);
}

table tbody {
    background: rgba(0,0,0,0.05);
}

table tfoot {
    background: rgba(0,0,0,0.15);
    border: 1px solid rgba(0,0,0,0.15);
    border-top: 1px solid rgba(0,0,0,0.2);
}

figure {
    display: inline-block;
    position: relative;
    margin: 1em 0 2em;
}

figcaption {
    font-style: italic;
    text-align: center;
    background: white;
    color: #6f6f6f;
    position: absolute;
    left: 0;
    bottom: -24px;
    width: 98%;
    padding: 1%;
    -webkit-transition: all .2s ease-in-out;
    -moz-transition: all .2s ease-in-out;
    -o-transition: all .2s ease-in-out;
    -ms-transition: all .2s ease-in-out;
    transition: all .2s ease-in-out;
}

figure:hover>figcaption {
    /* background: rgba(0,0,0,1) */
}

.poetry pre {
    display: block;
    font-family: adobe-caslon-pro, Georgia, serif;
    font-size: 110%;
    font-style: italic;
    line-height: 1.6em;
    margin-left: 1em;
}

.poetry pre code {
    font-family: adobe-caslon-pro, Georgia, serif;
}

 p {
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    color: #333333;
    border-left: 2.5px solid #00006b;
}

sup,sub,a.footnote {
    font-size: 1.4ex;
    height: 0;
    line-height: 1;
    position: relative;
    vertical-align: super;
}

sub {
    vertical-align: sub;
    top: -1px;
}

p,h5 {
    font-size: 1.1429em;
    line-height: 1.3125em;
    margin: 1.3125em 0;
}

dt,th {
    font-weight: 700;
}

table tr:nth-child(odd),table th:nth-child(odd),table td:nth-child(odd) {
    background: #fff4e6;
}

table tr:nth-child(even),table td:nth-child(even) {
    background: #fffdeb;
}

@media print {
    body {
        overflow: auto;
    }

    img,pre,,table,figure,p {
        page-break-inside: avoid;
    }

    #wrapper {
        background: #fff4e6;
        color: #1c0021;
        font-size: 85%;
        padding: 10px;
        position: relative;
        text-indent: 0;
    }
}

@media screen {
    .inverted #wrapper,.inverted {
        background: #1c0021;
    }

    .inverted hr {
        border-color: #1c0021;
    }

    .inverted p,.inverted td,.inverted li,.inverted h1,.inverted h2,.inverted h3,.inverted h4,.inverted h5,.inverted h6,.inverted pre,.inverted code,.inverted th,.inverted .math,.inverted caption,.inverted dd,.inverted dt {
        color: #fffdeb;
    }

    .inverted table tr:nth-child(odd),.inverted table th:nth-child(odd),.inverted table td:nth-child(odd) {
        background: none;
    }

    .inverted a {
        color: #da2573;
    }

    #wrapper {
        padding: 20px;
    }

    ::selection {
        background: #da2573;
    }

    h1::selection {
        background-color: #da2573;
    }

    h2::selection {
        background-color: #da2573;
    }

    h3::selection,h4::selection,h5::selection,h6::selection,li::selection,ol::selection {
        background-color: #da2573;
    }

    code::selection {
        background-color: #6f6f6f;
        color: #fffdeb;
    }

    code span::selection {
        background-color: #fffdeb;
        color: #fff4e6;
    }

    a::selection {
        background-color: #f7ff85;
    }

    .inverted a::selection {
        background-color: #f7ff85;
    }

    td::selection,th::selection,caption::selection {
        background-color: #da2573;
    }
}

.gist {
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
    font-size: 18px;
}

.gist .gist-meta {
    font-family: proxima-nova-extra-condensed, sans-serif;
    font-weight: 600;
    color: #1c0021;
}

.gist, .gist article, .gist article p {
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
}


.gist .gist-file .gist-data {
    background: #FFFdeb;;
    border: 1px solid #da2573;
    border-radius: 1px;
    font-size: 0.85em;
    color: #1c0021;
    font-family: proxima-nova-condensed, sans-serif;
    font-weight: 400;
}

.gist, .gist article, .gist article p {
    white-space: normal;
}
```
